name: Build Installer
on:
  push:
    branches: [ "main" ]

jobs:
  build:
    name: Build the Inno Setup Installer
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - name: Compile .ISS to .EXE Installer
        uses: Minionguyjpro/Inno-Setup-Action@v1.2.6
        with:
          path: installer/LEOinstaller.iss

      - name: Rename .EXE file
        run:
          move installer\Output\mysetup.exe installer\Output\setup_LEO.exe

      - uses: actions/upload-artifact@v4
        with:
          name: Setup_LEO
          path: installer/Output/setup_LEO.exe
